# Generated by Django 3.1.1 on 2020-09-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='project',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='anonymous',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.project'),
        ),
    ]
